# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a630bcd02b48ddd2ed2b655fcae8f2a41faa360524154de0b39bfba7e80306371d6e19f25fae2a31fe99064bf53a3620ac056a603563d7f0039f8d1a1ea3dde

test:
  secret_key_base: 4d87cec4f8b9e18c87762556704867f54facff068e52218e0d8a8bb474bd540b35ef226a5236e1be10f2194e5456dc7ca6f83f98b56d0b789a9bf9690b97c933

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
